config/routes.rb
Viewhr::Application.routes.draw do
  resources :interviews

  resources :mandates

  resources :applicants

end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
has_many :interviews
has_many :mandate, :through => :interview
end

app/models/interview.rb
class Interview < ActiveRecord::Base
  belongs_to :applicant
  belongs_to :mandate
validates_presence_of :mandate_id
validates_presence_of :applicant_id
end

app/models/mandate.rb
class Mandate < ActiveRecord::Base
has_many :interviews
has_many :applicants, :through => :interview
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  # GET /applicants
  # GET /applicants.xml
  def index
    @applicants = Applicant.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @applicants }
    end
  end

  # GET /applicants/1
  # GET /applicants/1.xml
  def show
    @applicant = Applicant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @applicant }
    end
  end

  # GET /applicants/new
  # GET /applicants/new.xml
  def new
    @applicant = Applicant.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @applicant }
    end
  end

  # GET /applicants/1/edit
  def edit
    @applicant = Applicant.find(params[:id])
  end

  # POST /applicants
  # POST /applicants.xml
  def create
    @applicant = Applicant.new(params[:applicant])

    respond_to do |format|
      if @applicant.save
        format.html { redirect_to(@applicant, :notice => 'Applicant was successfully created.') }
        format.xml  { render :xml => @applicant, :status => :created, :location => @applicant }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @applicant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /applicants/1
  # PUT /applicants/1.xml
  def update
    @applicant = Applicant.find(params[:id])

    respond_to do |format|
      if @applicant.update_attributes(params[:applicant])
        format.html { redirect_to(@applicant, :notice => 'Applicant was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @applicant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /applicants/1
  # DELETE /applicants/1.xml
  def destroy
    @applicant = Applicant.find(params[:id])
    @applicant.destroy

    respond_to do |format|
      format.html { redirect_to(applicants_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  # GET /interviews
  # GET /interviews.xml
  def index
    @interviews = Interview.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @interviews }
    end
  end

  # GET /interviews/1
  # GET /interviews/1.xml
  def show
    @interview = Interview.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @interview }
    end
  end

  # GET /interviews/new
  # GET /interviews/new.xml
  def new
    @interview = Interview.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @interview }
    end
  end

  # GET /interviews/1/edit
  def edit
    @interview = Interview.find(params[:id])
  end

  # POST /interviews
  # POST /interviews.xml
  def create
    @interview = Interview.new(params[:interview])

    respond_to do |format|
      if @interview.save
        format.html { redirect_to(@interview, :notice => 'Interview was successfully created.') }
        format.xml  { render :xml => @interview, :status => :created, :location => @interview }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @interview.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /interviews/1
  # PUT /interviews/1.xml
  def update
    @interview = Interview.find(params[:id])

    respond_to do |format|
      if @interview.update_attributes(params[:interview])
        format.html { redirect_to(@interview, :notice => 'Interview was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @interview.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /interviews/1
  # DELETE /interviews/1.xml
  def destroy
    @interview = Interview.find(params[:id])
    @interview.destroy

    respond_to do |format|
      format.html { redirect_to(interviews_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/mandates_controller.rb
class MandatesController < ApplicationController
  # GET /mandates
  # GET /mandates.xml
  def index
    @mandates = Mandate.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @mandates }
    end
  end

  # GET /mandates/1
  # GET /mandates/1.xml
  def show
    @mandate = Mandate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mandate }
    end
  end

  # GET /mandates/new
  # GET /mandates/new.xml
  def new
    @mandate = Mandate.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mandate }
    end
  end

  # GET /mandates/1/edit
  def edit
    @mandate = Mandate.find(params[:id])
  end

  # POST /mandates
  # POST /mandates.xml
  def create
    @mandate = Mandate.new(params[:mandate])

    respond_to do |format|
      if @mandate.save
        format.html { redirect_to(@mandate, :notice => 'Mandate was successfully created.') }
        format.xml  { render :xml => @mandate, :status => :created, :location => @mandate }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mandate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /mandates/1
  # PUT /mandates/1.xml
  def update
    @mandate = Mandate.find(params[:id])

    respond_to do |format|
      if @mandate.update_attributes(params[:mandate])
        format.html { redirect_to(@mandate, :notice => 'Mandate was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mandate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mandates/1
  # DELETE /mandates/1.xml
  def destroy
    @mandate = Mandate.find(params[:id])
    @mandate.destroy

    respond_to do |format|
      format.html { redirect_to(mandates_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/mandates_helper.rb
module MandatesHelper
end

app/views/applicants/_form.html.erb
<%= form_for(@applicant) do |f| %>
  <% if @applicant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@applicant.errors.count, "error") %> prohibited this applicant from being saved:</h2>

      <ul>
      <% @applicant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dob %><br />
    <%= f.date_select :dob, :start_year => Time.now.year-35, :end_year => Time.now.year-20 %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :qualification %><br />
    <%= f.text_field :qualification %>
  </div>
  <div class="field">
    <%= f.label :experience %><br />
    <%= f.text_field :experience %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applicants/edit.html.erb
<h1>Editing applicant</h1>

<%= render 'form' %>

<%= link_to 'Show', @applicant %> |
<%= link_to 'Back', applicants_path %>

app/views/applicants/index.html.erb
<h1>Listing applicants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Dob</th>
    <th>Address</th>
    <th>Photo</th>
    <th>Qualification</th>
    <th>Experience</th>
    <th>Phone</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @applicants.each do |applicant| %>
  <tr>
    <td><%= applicant.name %></td>
    <td><%= applicant.dob %></td>
    <td><%= applicant.address %></td>
    <td><%= applicant.photo %></td>
    <td><%= applicant.qualification %></td>
    <td><%= applicant.experience %></td>
    <td><%= applicant.phone %></td>
    <td><%= applicant.email %></td>
    <td><%= link_to 'Show', applicant %></td>
    <td><%= link_to 'Edit', edit_applicant_path(applicant) %></td>
    <td><%= link_to 'Destroy', applicant, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Applicant', new_applicant_path %>

app/views/applicants/new.html.erb
<h1>New applicant</h1>

<%= render 'form' %>

<%= link_to 'Back', applicants_path %>

app/views/applicants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @applicant.name %>
</p>

<p>
  <b>Dob:</b>
  <%= @applicant.dob %>
</p>

<p>
  <b>Address:</b>
  <%= @applicant.address %>
</p>

<p>
  <b>Photo:</b>
  <%= @applicant.photo %>
</p>

<p>
  <b>Qualification:</b>
  <%= @applicant.qualification %>
</p>

<p>
  <b>Experience:</b>
  <%= @applicant.experience %>
</p>

<p>
  <b>Phone:</b>
  <%= @applicant.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @applicant.email %>
</p>


<%= link_to 'Edit', edit_applicant_path(@applicant) %> |
<%= link_to 'Back', applicants_path %>

app/views/interviews/_form.html.erb
<%= form_for(@interview) do |f| %>
  <% if @interview.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interview.errors.count, "error") %> prohibited this interview from being saved:</h2>

      <ul>
      <% @interview.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :applicant %><br />
    <%= f.collection_select :applicant_id, Applicant.all, :id, :name, {:prompt => "Select Applicant"} %>
  </div>
  <div class="field">
    <%= f.label :mandate %><br />
    <%= f.collection_select :mandate_id, Mandate.all, :id, :name, {:prompt => "Select Mandate"} %>
  </div>
  <div class="field">
    <%= f.label :date_of_conducting %><br />
    <%= f.text_field :date_of_conducting %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interviews/edit.html.erb
<h1>Editing interview</h1>

<%= render 'form' %>

<%= link_to 'Show', @interview %> |
<%= link_to 'Back', interviews_path %>

app/views/interviews/index.html.erb
<h1>Listing interviews</h1>

<table>
  <tr>
    <th>Applicant</th>
    <th>Mandate</th>
    <th>Date of conducting</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @interviews.each do |interview| %>
  <tr>
    <td><%= interview.applicant.name %></td>
    <td><%= interview.mandate.name %></td>
    <td><%= interview.date_of_conducting %></td>
    <td><%= interview.description %></td>
    <td><%= link_to 'Show', interview %></td>
    <td><%= link_to 'Edit', edit_interview_path(interview) %></td>
    <td><%= link_to 'Destroy', interview, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Interview', new_interview_path %>

app/views/interviews/new.html.erb
<h1>New interview</h1>

<%= render 'form' %>

<%= link_to 'Back', interviews_path %>

app/views/interviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Applicant:</b>
  <%= @interview.applicant.name %>
</p>

<p>
  <b>Mandate:</b>
  <%= @interview.mandate.name %>
</p>

<p>
  <b>Date of conducting:</b>
  <%= @interview.date_of_conducting %>
</p>

<p>
  <b>Description:</b>
  <%= @interview.description %>
</p>


<%= link_to 'Edit', edit_interview_path(@interview) %> |
<%= link_to 'Back', interviews_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
 <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>

<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>

<%= csrf_meta_tag %>

  <title>Viewhr</title>
  
</head>
<body bgcolor=yellow>

<%= yield %>

</body>
</html>

app/views/mandates/_form.html.erb
<%= form_for(@mandate) do |f| %>
  <% if @mandate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mandate.errors.count, "error") %> prohibited this mandate from being saved:</h2>

      <ul>
      <% @mandate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :company_name %><br />
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mandates/edit.html.erb
<h1>Editing mandate</h1>

<%= render 'form' %>

<%= link_to 'Show', @mandate %> |
<%= link_to 'Back', mandates_path %>

app/views/mandates/index.html.erb
<h1>Listing mandates</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Company name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mandates.each do |mandate| %>
  <tr>
    <td><%= mandate.name %></td>
    <td><%= mandate.company_name %></td>
    <td><%= mandate.description %></td>
    <td><%= link_to 'Show', mandate %></td>
    <td><%= link_to 'Edit', edit_mandate_path(mandate) %></td>
    <td><%= link_to 'Destroy', mandate, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mandate', new_mandate_path %>

app/views/mandates/new.html.erb
<h1>New mandate</h1>

<%= render 'form' %>

<%= link_to 'Back', mandates_path %>

app/views/mandates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mandate.name %>
</p>

<p>
  <b>Company name:</b>
  <%= @mandate.company_name %>
</p>

<p>
  <b>Description:</b>
  <%= @mandate.description %>
</p>


<%= link_to 'Edit', edit_mandate_path(@mandate) %> |
<%= link_to 'Back', mandates_path %>